"""Fertige, gepruefte Vergleichsskripte fuer den kostenlosen Betrieb.

Seit 01.10.2026 laeuft The Difference Money ohne bezahlte API (Emre: "lokal
ohne Kosten"). Ohne Skript aus dieser Sammlung springt die allgemeine Vorlage
aus local_versus.py ein - die ist brauchbar, aber blass. Deshalb schreibt
Claude hier in einer Abo-Sitzung echte Skripte im Kanalformat; der
woechentliche Kanal-Agent ergaenzt neue (Regeln in
~/Projects/kanal-waechter/AGENTEN.md).

Jedes Skript muss versus_gen.pruefe() bestehen: 8-11 Saetze, Einstieg
hoechstens 90 Zeichen, ein Satz beginnt mit "The difference", keine
Empfehlung, keine Werbesprache. Zahlen werden ausgeschrieben, wie man sie
spricht.
"""


def S(text, pose="stehen", icon=None, wort=None, stimmung=0.0, diagramm=None):
    return {"text": text, "pose": pose, "icon": icon, "wort": wort,
            "stimmung": stimmung, "diagramm": diagramm}


def folge(thema, a, b, zeile, icon, saetze, beschreibung, hashtags, zahl=None,
          ueberschrift=None):
    return {
        "thema": thema,
        "begriffe": [a, b],
        "ueberschrift": ueberschrift or f"{a} vs {b}",
        "titel": f"{a} vs {b} - What's the Difference?",
        "beschreibung": beschreibung,
        "tags": [a, b, "Personal finance", "Money basics", "Comparison"],
        "hashtags": hashtags,
        "thumbnail": {"zeile": zeile, "zahl": zahl, "icon": icon},
        "saetze": saetze,
    }


SKRIPTE = [
    folge("Cashback vs Rewards points", "Cashback", "Rewards points",
          "cash or points", "muenze", [
              S("Two cards both promise you something back. Only one tells you what it is worth.", "denken", "muenze", stimmung=0.1),
              S("Once you see how each one is counted, the choice looks very different.", "zeigen"),
              S("Cashback is simple: a percentage of what you spend comes back to you as money.", "stehen", "prozent", "2%", 0.2),
              S("Spend a thousand dollars at two percent, and twenty dollars come back. Done.", "jubeln", "muenze", stimmung=0.3,
                diagramm={"art": "balken", "werte": [1000, 20], "achse": ["spent", "back"], "einheit": "$"}),
              S("Rewards points are a currency the card company invents and values itself.", "denken", "stapel", "POINTS"),
              S("One point might be worth one cent as cash, or two cents when used for flights.", "zeigen", "balken"),
              S("And the company can change that value later, which is called a devaluation.", "achselzucken", "runter", stimmung=-0.3),
              S("The difference: cashback has a fixed value in money, points only have the value you can redeem.", "stehen", "waage", stimmung=0),
              S("It matters most when you compare offers, because a big number of points can be small in dollars.", "denken", "schere"),
              S("Cashback is money you can count. Points are a promise you have to translate first.", "sitzen", stimmung=0.1),
          ],
          "How cashback and rewards points really differ: fixed money back versus a currency the card company values itself.",
          ["#cashback", "#creditcards", "#rewardspoints", "#personalfinance"]),

    folge("Duration vs Maturity", "Duration", "Maturity",
          "time vs risk", "uhr", [
              S("Two bonds both end in ten years. One can still lose far more when rates move.", "denken", "uhr", stimmung=-0.2),
              S("Two words explain why, and they sound like they mean the same thing.", "zeigen"),
              S("Maturity is simply the date the bond ends and pays back what you lent.", "stehen", "uhr", "10 YEARS"),
              S("A ten year bond has a maturity of ten years. That is a calendar fact.", "zeigen", "uhr"),
              S("Duration measures how sensitive the bond's price is to a change in interest rates.", "denken", "kurve", "DURATION"),
              S("With a duration of seven, a one point rise in rates cuts the price by roughly seven percent.", "zeigen", "runter", stimmung=-0.3,
                diagramm={"art": "balken", "werte": [100, 93], "achse": ["before", "after rates rise"], "einheit": "$"}),
              S("Bonds that pay interest along the way have a duration shorter than their maturity.", "sitzen", "prozent"),
              S("The difference: maturity tells you when the bond ends, duration tells you how hard its price swings.", "stehen", "waage"),
              S("It matters when rates change, because two bonds with the same end date can react very differently.", "denken", "hoch"),
              S("Maturity is the finish line. Duration is how bumpy the road feels on the way there.", "sitzen", stimmung=0.1),
          ],
          "Duration and maturity explained with one number example: why two bonds with the same end date can react differently to interest rates.",
          ["#bonds", "#duration", "#interestrates", "#investing101"], zahl="7%"),

    folge("Prepaid card vs Debit card", "Prepaid card", "Debit card",
          "whose money?", "bank", [
              S("Both cards spend money you already have. Only one is connected to your bank account.", "denken", "bank"),
              S("That one link changes what can go wrong.", "zeigen"),
              S("A debit card is tied to your checking account, and every purchase comes straight out of it.", "stehen", "bank", "DEBIT"),
              S("Depending on your bank's settings, you can even spend more than you have and pay an overdraft fee.", "achselzucken", "schere", stimmung=-0.3),
              S("A prepaid card is loaded with money in advance, like a gift card you can top up.", "zeigen", "muenze", "PREPAID"),
              S("When the loaded amount is gone, the card simply stops working.", "sitzen", "runter"),
              S("The difference: a debit card draws from your bank account, a prepaid card only holds what you put on it.", "stehen", "waage"),
              S("It matters if the card is stolen, because a thief with a prepaid card can only reach what is loaded.", "denken"),
              S("Neither one builds a credit history, because neither one is a loan.", "zeigen", "prozent"),
              S("Debit is a window into your account. Prepaid is a separate wallet with a fixed amount.", "sitzen", stimmung=0.1),
          ],
          "Prepaid card versus debit card: where the money comes from, overdrafts, theft and why neither builds credit.",
          ["#debitcard", "#prepaidcard", "#banking", "#moneybasics"]),

    folge("Margin vs Leverage", "Margin", "Leverage",
          "loan vs multiplier", "waage", [
              S("Margin and leverage get used as if they were one word. One is a tool, one is the effect.", "denken", "waage"),
              S("A simple number example shows which is which.", "zeigen"),
              S("Margin is money borrowed from your broker, with the investments in your account as security.", "stehen", "bank", "MARGIN"),
              S("You have a thousand dollars and borrow another thousand on margin to invest two thousand.", "zeigen", "stapel"),
              S("Leverage is the multiplier: you now control twice as much as your own money.", "denken", "hoch", "2X"),
              S("If the investment falls ten percent, you lose two hundred dollars, which is twenty percent of your own money.", "achselzucken", "runter", stimmung=-0.4,
                diagramm={"art": "balken", "werte": [10, 20], "achse": ["market drop", "your loss"], "einheit": "%"}),
              S("If it falls too far, the broker can demand more money. That is called a margin call.", "sitzen", "schere", stimmung=-0.3),
              S("The difference: margin is one way to borrow, leverage is how much the borrowing multiplies gains and losses.", "stehen", "waage"),
              S("You can have leverage without margin, for example through a mortgage or certain funds.", "zeigen", "haus"),
              S("Margin is the loan. Leverage is what that loan does to every move afterwards.", "sitzen"),
          ],
          "Margin versus leverage with a two-thousand-dollar example: how borrowing multiplies both gains and losses, and what a margin call is.",
          ["#leverage", "#margin", "#investing101", "#risk"], zahl="2x"),

    folge("Grace period vs Due date", "Grace period", "Due date",
          "when interest starts", "uhr", [
              S("Paying your card on the due date is not always the same as paying no interest.", "denken", "uhr"),
              S("The gap between those two ideas has a name.", "zeigen"),
              S("The due date is the deadline for at least the minimum payment on your credit card statement.", "stehen", "uhr", "DUE"),
              S("Miss it, and you can face a late fee and a mark on your credit report.", "achselzucken", "schere", stimmung=-0.3),
              S("The grace period is the time between the end of your statement and that due date.", "zeigen", "uhr", "GRACE"),
              S("In the US, card issuers must give you at least twenty one days for it.", "sitzen", "bank", "21 DAYS"),
              S("Pay the full balance within it, and new purchases usually cost no interest at all.", "jubeln", "prozent", stimmung=0.3),
              S("The difference: the due date avoids late fees, the grace period with a full payment avoids interest.", "stehen", "waage"),
              S("It matters if you pay only the minimum, because interest then usually starts building on the rest.", "denken", "hoch", stimmung=-0.2),
              S("The due date is the deadline. The grace period is the interest free window before it.", "sitzen", stimmung=0.1),
          ],
          "Grace period versus due date on a credit card: which one protects you from late fees and which one from interest.",
          ["#creditcard", "#interest", "#creditscore", "#moneybasics"]),

    folge("Market order vs Limit order", "Market order", "Limit order",
          "speed or price", "uhr", [
              S("Two people click buy on the same share. One gets it now, the other gets their price.", "denken", "uhr"),
              S("Which one you get depends on the order type.", "zeigen"),
              S("A market order says: buy or sell right away at the best price available.", "stehen", "uhr", "NOW"),
              S("It almost always goes through, but in a fast market the price can be a bit worse than expected.", "achselzucken", "runter", stimmung=-0.2),
              S("A limit order says: only at this price or better.", "zeigen", "prozent", "LIMIT"),
              S("Set a limit of fifty dollars, and you will never pay fifty one for that share.", "sitzen", "muenze"),
              S("But if the price never reaches fifty, the order may simply never be filled.", "denken", "uhr", stimmung=-0.1),
              S("The difference: a market order guarantees the trade, a limit order guarantees the price.", "stehen", "waage"),
              S("It matters most for shares that trade rarely, where prices can jump between two trades.", "denken", "kurve"),
              S("Market order means certainty about speed. Limit order means certainty about price.", "sitzen", stimmung=0.1),
          ],
          "Market order versus limit order: one guarantees the trade, the other guarantees the price. Explained with a fifty-dollar example.",
          ["#stockmarket", "#trading101", "#limitorder", "#investing101"]),

    folge("Co-signer vs Guarantor", "Co-signer", "Guarantor",
          "who pays when", "waage", [
              S("Signing for someone else's loan sounds kind. How much risk you take depends on one word.", "denken", "waage"),
              S("Co-signer and guarantor are not always the same promise.", "zeigen"),
              S("A co-signer signs the loan alongside the borrower and is usually responsible from day one.", "stehen", "bank", "CO-SIGNER"),
              S("The lender can ask the co-signer for payment just as easily as the borrower.", "achselzucken", "muenze", stimmung=-0.2),
              S("A guarantor promises to pay only if the borrower fails to pay.", "zeigen", "schere", "GUARANTOR"),
              S("The lender usually has to go to the borrower first before turning to the guarantor.", "sitzen", "uhr"),
              S("The difference: a co-signer shares the debt from the start, a guarantor steps in only as a backup.", "stehen", "waage"),
              S("The exact rules depend on the contract and the country, so the wording of the document decides.", "denken"),
              S("It matters for your own credit, because a missed payment can show up on your report too.", "achselzucken", "runter", stimmung=-0.3),
              S("A co-signer is a second borrower. A guarantor is a safety net behind the first one.", "sitzen", stimmung=0),
          ],
          "Co-signer versus guarantor: when each one has to pay, and why the contract wording decides.",
          ["#loans", "#cosigner", "#credit", "#moneybasics"]),

    folge("Bid vs Ask spread", "Bid", "Ask",
          "the hidden cost", "schere", [
              S("Buy a share and sell it a second later. You already lost money. Here is why.", "denken", "schere", stimmung=-0.2),
              S("Every price on a screen is really two prices.", "zeigen"),
              S("The bid is the highest price a buyer is currently willing to pay.", "stehen", "muenze", "BID"),
              S("The ask is the lowest price a seller is currently willing to accept.", "zeigen", "muenze", "ASK"),
              S("If the bid is ninety nine dollars ninety and the ask is a hundred ten, the gap is twenty cents.", "sitzen", "balken",
                diagramm={"art": "balken", "werte": [99.9, 100.1], "achse": ["bid", "ask"], "einheit": "$"}),
              S("You buy at the ask and sell at the bid, so a round trip right away costs you that gap.", "achselzucken", "runter", stimmung=-0.3),
              S("The difference: the bid is what you get when you sell, the ask is what you pay when you buy.", "stehen", "waage"),
              S("The gap is called the spread, and it is wider for things that are traded rarely.", "denken", "schere", "SPREAD"),
              S("It matters for frequent trading, where small spreads add up to real costs.", "zeigen", "stapel"),
              S("The bid is the buyer's price. The ask is the seller's price. The spread lives in between.", "sitzen", stimmung=0.1),
          ],
          "Bid versus ask and the spread between them: the cost you pay on every trade, explained with a twenty-cent example.",
          ["#stockmarket", "#bidask", "#spread", "#investing101"], zahl="20¢", ueberschrift="Bid vs Ask"),

    folge("Refinance vs Consolidate", "Refinance", "Consolidate",
          "new loan or one loan", "bank", [
              S("Both promise a better loan. One changes a loan, the other combines several.", "denken", "bank"),
              S("They overlap, but they solve different problems.", "zeigen"),
              S("To refinance means replacing an existing loan with a new one on different terms.", "stehen", "bank", "REFINANCE"),
              S("Someone with a mortgage at seven percent might refinance into one at six.", "zeigen", "prozent", stimmung=0.2),
              S("To consolidate means rolling several debts into a single loan with one payment.", "sitzen", "stapel", "CONSOLIDATE"),
              S("Three credit cards and a store loan become one monthly bill.", "zeigen", "korb"),
              S("The difference: refinancing changes the terms of a debt, consolidating changes how many debts you have.", "stehen", "waage"),
              S("A consolidation loan is often also a refinance, if the new rate is lower.", "denken"),
              S("Either way, a longer term can mean more interest overall, even with a lower monthly payment.", "achselzucken", "uhr", stimmung=-0.2),
              S("Refinance swaps a loan. Consolidate merges loans. Sometimes one step does both.", "sitzen", stimmung=0.1),
          ],
          "Refinance versus consolidate: changing the terms of a loan versus combining several debts into one.",
          ["#debt", "#refinance", "#loans", "#personalfinance"]),

    folge("Yield to maturity vs Coupon rate", "Yield to maturity", "Coupon rate",
          "same bond, two rates", "prozent", [
              S("A bond says five percent on the label. You might still earn more, or less.", "denken", "prozent"),
              S("That is because a bond has two different rates.", "zeigen"),
              S("The coupon rate is the fixed interest the bond pays on its face value, usually a thousand dollars.", "stehen", "prozent", "COUPON"),
              S("A five percent coupon pays fifty dollars a year, no matter what the bond costs later.", "zeigen", "muenze"),
              S("Yield to maturity is the yearly return you get if you buy at today's price and hold until the end.", "denken", "kurve", "YIELD"),
              S("Buy that bond for nine hundred dollars, and you also gain a hundred at the end, so your yield is above five.", "jubeln", "hoch", stimmung=0.3,
                diagramm={"art": "balken", "werte": [900, 1000], "achse": ["price paid", "paid back"], "einheit": "$"}),
              S("The difference: the coupon rate is fixed by the bond, the yield to maturity depends on the price you pay.", "stehen", "waage"),
              S("When market rates rise, bond prices fall, and yields climb above the coupon.", "zeigen", "runter"),
              S("It matters when comparing bonds, because the coupon alone hides what you actually earn.", "denken", "balken"),
              S("The coupon is what the bond pays. The yield is what you earn at the price you paid.", "sitzen", stimmung=0.1),
          ],
          "Yield to maturity versus coupon rate: why a five percent bond can earn you more or less than five percent.",
          ["#bonds", "#yield", "#fixedincome", "#investing101"], zahl="5%", ueberschrift="Yield to Maturity vs Coupon"),

    folge("Lease vs Finance", "Lease", "Finance",
          "rent it or own it", "haus", [
              S("Two people drive the same new car for the same monthly payment. Only one will own it.", "denken", "muenze"),
              S("Leasing and financing work in opposite directions.", "zeigen"),
              S("When you lease, you pay for the part of the car's value that is used up while you drive it.", "stehen", "runter", "LEASE"),
              S("At the end, you give it back, and there are usually limits on how many miles you can drive.", "achselzucken", "uhr"),
              S("When you finance, you take a loan to buy the whole car and pay it off over time.", "zeigen", "bank", "LOAN"),
              S("Once the loan is paid, the car is yours, with no mileage limit.", "jubeln", "stapel", stimmung=0.3),
              S("The difference: leasing is paying to use the car, financing is paying to own it.", "stehen", "waage"),
              S("Lease payments are often lower, because you do not pay for the car's full value.", "denken", "schere"),
              S("It matters for how long you keep cars, and how far you drive them.", "zeigen", "uhr"),
              S("A lease is a long rental. Financing is a purchase on installments.", "sitzen", stimmung=0.1),
          ],
          "Leasing versus financing a car: paying for use versus paying for ownership, mileage limits and why lease payments are lower.",
          ["#carlease", "#carloan", "#personalfinance", "#moneybasics"]),

    folge("Hedging vs Speculation", "Hedging", "Speculation",
          "same tool, other goal", "waage", [
              S("Two people sign the exact same contract. One is reducing risk, the other is seeking it.", "denken", "waage"),
              S("The contract is identical. The intention is not.", "zeigen"),
              S("Hedging means taking a position that protects you against a risk you already have.", "stehen", "schere", "HEDGE"),
              S("A wheat farmer can lock in today's price for the harvest, so a price crash does not ruin the year.", "sitzen", "korb", stimmung=0.2),
              S("Speculation means taking on risk on purpose, hoping to profit from a price move.", "zeigen", "hoch", "SPECULATE"),
              S("A trader with no farm can make the same bet on wheat, simply to profit if prices move his way.", "denken", "kurve"),
              S("The difference: a hedger is trying to lose less, a speculator is trying to win more.", "stehen", "waage"),
              S("Markets need both, because the speculator often takes the risk the hedger wants to get rid of.", "zeigen", "balken"),
              S("It matters for judging a trade, because the same position can be careful or risky.", "denken"),
              S("Hedging is insurance against a move. Speculation is a bet on a move.", "sitzen", stimmung=0.1),
          ],
          "Hedging versus speculation: the same contract can reduce risk or create it. Explained with a wheat farmer.",
          ["#hedging", "#speculation", "#derivatives", "#economics"]),

    folge("Copay vs Deductible", "Copay", "Deductible",
          "who pays first", "schere", [
              S("You have health insurance and still get a bill. Two words usually explain it.", "denken", "schere", stimmung=-0.2),
              S("They describe different parts of what you pay yourself.", "zeigen"),
              S("A deductible is the amount you pay for covered care before your insurance starts sharing the cost.", "stehen", "stapel", "DEDUCTIBLE"),
              S("With a one thousand dollar deductible, the first thousand of covered bills is mostly yours.", "zeigen", "muenze"),
              S("A copay is a fixed fee for a specific service, like twenty five dollars for a doctor visit.", "sitzen", "muenze", "COPAY"),
              S("In many plans, copays apply to some services even before the deductible is reached.", "denken", "uhr"),
              S("The difference: the deductible is a yearly amount you pay first, a copay is a flat fee per visit.", "stehen", "waage"),
              S("It matters when you compare plans, because a low premium often comes with a high deductible.", "zeigen", "balken"),
              S("The exact rules are in your plan documents, and they differ from plan to plan.", "achselzucken"),
              S("The deductible is your share up front. The copay is your share each time.", "sitzen", stimmung=0.1),
          ],
          "Copay versus deductible in health insurance: a yearly amount you pay first versus a flat fee per visit.",
          ["#healthinsurance", "#deductible", "#copay", "#moneybasics"]),

    folge("Dollar cost averaging vs Lump sum", "Dollar cost averaging", "Lump sum",
          "all now or bit by bit", "uhr", [
              S("Twelve thousand dollars to invest. All of it today, or a thousand each month?", "denken", "stapel"),
              S("Both approaches have names, and the research on them is surprising.", "zeigen"),
              S("Lump sum means investing the whole amount at once.", "stehen", "stapel", "ALL AT ONCE"),
              S("Dollar cost averaging means splitting it into equal amounts invested at regular intervals.", "zeigen", "uhr", "MONTHLY"),
              S("Because the amount is fixed, you automatically buy more shares when prices are low.", "sitzen", "runter"),
              S("A Vanguard study found the lump sum came out ahead about two thirds of the time in the past.", "denken", "balken",
                diagramm={"art": "balken", "werte": [67, 33], "achse": ["lump sum ahead", "averaging ahead"], "einheit": "%"}),
              S("That is mainly because markets rose more often than they fell, so money waiting on the side missed out.", "zeigen", "hoch"),
              S("The difference: lump sum takes all the timing risk at once, averaging spreads it out over time.", "stehen", "waage"),
              S("It matters for how a fall right after investing would feel, which is a personal question, not a formula.", "achselzucken"),
              S("Lump sum is one decision. Dollar cost averaging is many small ones in a row.", "sitzen", stimmung=0.1),
          ],
          "Dollar cost averaging versus lump sum investing: how each works and what historical research found. Educational, not advice.",
          ["#dollarcostaveraging", "#investing101", "#lumpsum", "#personalfinance"], zahl="2/3", ueberschrift="Averaging vs Lump Sum"),

    folge("Tip vs Service charge", "Tip", "Service charge",
          "your choice or not", "korb", [
              S("Your restaurant bill already has eighteen percent added. Is that the tip?", "denken", "korb"),
              S("Not necessarily, and the money may not even go to the same place.", "zeigen"),
              S("A tip is voluntary. You decide whether to give it and how much.", "stehen", "muenze", "TIP"),
              S("In the US, tips generally belong to the employees who served you.", "zeigen", "stapel"),
              S("A service charge is a fee the business adds itself, and you are expected to pay it.", "sitzen", "schere", "FEE"),
              S("The IRS treats a service charge as wages paid by the business, not as tips.", "denken", "bank"),
              S("The difference: a tip is your choice and goes to staff, a service charge is the business's price.", "stehen", "waage"),
              S("It matters when you read a bill, so you know whether a tip is already included or not.", "zeigen", "korb"),
              S("Rules differ by country, and in many places a tip is simply not expected at all.", "achselzucken"),
              S("A tip is a gift you choose. A service charge is part of the bill.", "sitzen", stimmung=0.1),
          ],
          "Tip versus service charge: what is voluntary, what is a fee, and who the money belongs to in the US.",
          ["#tipping", "#restaurants", "#moneybasics", "#personalfinance"], zahl="18%"),

    folge("Systematic vs Unsystematic risk", "Systematic risk", "Unsystematic risk",
          "can you spread it?", "balken", [
              S("Owning a hundred companies protects you from one kind of risk. Not from the other.", "denken", "balken"),
              S("Finance gives those two risks names.", "zeigen"),
              S("Unsystematic risk belongs to one company: a failed product, a scandal, a bad manager.", "stehen", "runter", "ONE COMPANY"),
              S("Spread your money over many companies, and one disaster only hurts a small part.", "sitzen", "balken", stimmung=0.2),
              S("Systematic risk hits almost everything at once: a recession, rising rates, a crisis.", "achselzucken", "runter", "WHOLE MARKET", -0.3),
              S("When the whole market falls, owning more companies does not stop the fall.", "zeigen", "kurve", stimmung=-0.2),
              S("The difference: unsystematic risk can be reduced by diversifying, systematic risk cannot.", "stehen", "waage"),
              S("That is why investors talk about getting paid for market risk, but not for single company risk.", "denken", "prozent"),
              S("It matters for understanding why a broad fund still goes down in a crash.", "zeigen"),
              S("One kind of risk shrinks when you spread out. The other comes with the market itself.", "sitzen", stimmung=0),
          ],
          "Systematic versus unsystematic risk: which risk diversification removes, and which one stays no matter what.",
          ["#risk", "#diversification", "#investing101", "#stockmarket"], ueberschrift="Systematic vs Unsystematic"),

    folge("Renters insurance vs Homeowners insurance", "Renters insurance", "Homeowners insurance",
          "walls or stuff", "haus", [
              S("A fire damages an apartment building. Whose insurance pays for what?", "denken", "haus", stimmung=-0.2),
              S("It depends on which of two policies you have.", "zeigen"),
              S("Renters insurance covers your belongings inside the home, not the building itself.", "stehen", "korb", "RENTER"),
              S("It usually also covers liability, if someone is hurt in your place and blames you.", "zeigen", "waage"),
              S("The building belongs to the landlord, so the landlord insures the walls and roof.", "sitzen", "haus"),
              S("Homeowners insurance covers the structure, plus your belongings and liability in one policy.", "zeigen", "haus", "OWNER"),
              S("The difference: renters insurance protects what you own inside, homeowners insurance also protects the house.", "stehen", "waage"),
              S("That is why renters insurance usually costs far less each month.", "denken", "schere"),
              S("It matters after a loss, because a renter without a policy often has to replace everything alone.", "achselzucken", "runter", stimmung=-0.3),
              S("Renters insurance covers your stuff. Homeowners insurance covers your stuff and the walls around it.", "sitzen", stimmung=0.1),
          ],
          "Renters insurance versus homeowners insurance: belongings and liability versus the building itself.",
          ["#rentersinsurance", "#homeinsurance", "#insurance", "#moneybasics"], ueberschrift="Renters vs Homeowners Insurance"),

    folge("Present value vs Future value", "Present value", "Future value",
          "money has a clock", "uhr", [
              S("A thousand dollars today and a thousand in a year are not worth the same.", "denken", "uhr"),
              S("Two simple ideas explain why, and they are mirror images.", "zeigen"),
              S("Future value asks: what will money today grow into, at a given interest rate?", "stehen", "kurve", "FUTURE"),
              S("A thousand dollars at five percent becomes one thousand fifty dollars after a year.", "jubeln", "hoch", stimmung=0.3,
                diagramm={"art": "balken", "werte": [1000, 1050], "achse": ["today", "in one year"], "einheit": "$"}),
              S("Present value asks the reverse: what is money in the future worth today?", "zeigen", "uhr", "PRESENT"),
              S("At five percent, one thousand fifty dollars next year is worth a thousand today.", "sitzen", "muenze"),
              S("The difference: future value moves money forward in time, present value moves it back.", "stehen", "waage"),
              S("It matters for loans, pensions and investments, which all compare money at different times.", "denken", "bank"),
              S("The higher the rate, the less a future payment is worth today.", "zeigen", "runter"),
              S("Future value grows money forward. Present value discounts it back to today.", "sitzen", stimmung=0.1),
          ],
          "Present value versus future value with one simple five percent example: the time value of money explained.",
          ["#timevalueofmoney", "#finance101", "#interest", "#economics"]),

    folge("Forward contract vs Futures contract", "Forward contract", "Futures contract",
          "private or public", "waage", [
              S("Both lock in a price today for a later deal. One is private, one trades on an exchange.", "denken", "waage"),
              S("That one detail changes almost everything about how they work.", "zeigen"),
              S("A forward contract is a private agreement between two parties, written to fit their needs.", "stehen", "bank", "FORWARD"),
              S("It is usually settled once, at the end, and each side depends on the other to keep its word.", "sitzen", "uhr"),
              S("A futures contract is standardized and traded on an exchange.", "zeigen", "balken", "FUTURES"),
              S("Gains and losses are settled every day, and a clearinghouse stands between the two sides.", "denken", "uhr"),
              S("The difference: a forward is a custom private deal, a futures contract is a standardized exchange product.", "stehen", "waage"),
              S("That is why futures carry less risk that the other side fails to pay.", "zeigen", "schere"),
              S("It matters for companies hedging prices, who must choose flexibility or safety.", "denken"),
              S("A forward is tailor made. A futures contract is off the rack, with a referee.", "sitzen", stimmung=0.1),
          ],
          "Forward contract versus futures contract: a private custom deal versus a standardized exchange product with daily settlement.",
          ["#derivatives", "#futures", "#forwards", "#finance101"], ueberschrift="Forward vs Futures"),

    folge("Garnishment vs Lien", "Garnishment", "Lien",
          "income or property", "bank", [
              S("Unpaid debt can follow you in two very different ways. One reaches your paycheck.", "denken", "bank", stimmung=-0.2),
              S("The other attaches itself to what you own.", "zeigen"),
              S("A garnishment is a court order that takes part of your wages or bank account to pay a debt.", "stehen", "schere", "GARNISH"),
              S("Your employer then sends part of each paycheck directly to the creditor.", "achselzucken", "runter", stimmung=-0.3),
              S("A lien is a legal claim on a piece of property, like a house or a car, as security for a debt.", "zeigen", "haus", "LIEN"),
              S("You can usually keep using the property, but selling it means the debt gets paid first.", "sitzen", "muenze"),
              S("The difference: a garnishment takes money as it comes in, a lien blocks the value of what you own.", "stehen", "waage"),
              S("Some liens are normal, like the one a bank holds on a car until the loan is paid.", "denken", "bank"),
              S("The exact rules and limits depend on where you live and the type of debt.", "zeigen"),
              S("Garnishment takes from your income. A lien holds on to your property.", "sitzen", stimmung=0),
          ],
          "Garnishment versus lien: taking money from wages versus a legal claim on property. Educational, not legal advice.",
          ["#debt", "#lien", "#garnishment", "#moneybasics"]),

    folge("Discount vs Rebate", "Discount", "Rebate",
          "now or later", "korb", [
              S("Twenty dollars off sounds the same either way. When you get it is the catch.", "denken", "korb"),
              S("Discount and rebate give the same savings on paper.", "zeigen"),
              S("A discount lowers the price at the moment you pay.", "stehen", "schere", "DISCOUNT"),
              S("The product costs eighty instead of a hundred, and that is the end of it.", "jubeln", "muenze", stimmung=0.3),
              S("A rebate means you pay the full price first and get money back later.", "zeigen", "uhr", "REBATE"),
              S("Usually you have to send a form, a receipt or a code, often before a deadline.", "sitzen", "uhr"),
              S("The difference: a discount is money you never spend, a rebate is money you have to claim back.", "stehen", "waage"),
              S("Many rebates are never claimed, because people forget or miss the deadline.", "achselzucken", "runter", stimmung=-0.2),
              S("It matters when comparing prices, because the rebate price is only real if you follow through.", "denken", "korb"),
              S("A discount saves you now. A rebate saves you only if you finish the paperwork.", "sitzen", stimmung=0.1),
          ],
          "Discount versus rebate: the same savings on paper, but one comes at checkout and one only if you claim it.",
          ["#shopping", "#discount", "#rebate", "#moneybasics"]),
]
